### ISSUE TITLE
Solve linear systems with multiple right hand sides

### ISSUE THREAD

**Issue by JonathanWenger** [probabilistic-numerics/probnum#302]
# Idea
The probabilistic linear solver can solve problems with multiple right hand sides `nrhs` by taking multiple actions at each iteration, one for each right hand side. The update for the matrix models can be performed for batch updates in the same manner as they are done now. 

## Remark
For a symmetric Kronecker product covariance the induced covariance takes the following form:

![IMG_6066](https://user-images.githubusercontent.com/29815984/104909481-33896a00-5988-11eb-824a-9a6602b0a4c2.jpg)

This requires the implementation of a `BoxProduct` linear operator.

# TODOs
- [ ] Implement `linops.BoxProduct`
- [ ] Refactor policies to return arrays
- [ ] Update induced solution random variable
