### ISSUE TITLE
Duplicate Type Definitions

### ISSUE THREAD

**Issue by JonathanWenger** [probabilistic-numerics/probnum#448]
# In a Nutshell
Duplicate types `ToleranceDiffusionType` and `DenseOutputLocationArgType`, which are just aliases for the same expression `Union[FloatArgType, np.ndarray]`

# In Detail
There are type definitions in `probnum.type`, which define the same general concept, namely a variable which is either a scalar or an array. Currently there are two overly specific names for this type, once given as an arg type, suggesting there is some type normalization coming after and once not. 

# TODO
- [ ] Investigate usages of `ToleranceDiffusionType` and `DenseOutputLocationArgType` to determine whether there is type normalization (meaning functionality which converts the input to a common type, e.g. a `np.array`) going on
- [ ] Define a single (argument) type `ScalarOrArrayArgType` superseding the overly specific types above or simply replace with `Union[FloatArgType, np.ndarray]`
- [ ] Move new arg type under Argument types in `probnum.type`
