### ISSUE TITLE
Random sparse matrices as example problems are dense

### ISSUE THREAD

**Issue by JonathanWenger** [probabilistic-numerics/probnum#452]
# In a Nutshell
The function generating random sparse matrices `probnum.problems.zoo.linalg.random_sparse_spd_matrix` returns a dense `np.ndarray` instead of a sparse data type.

# In Detail
Make sure a `scipy.sparse.csr_matrix` is generated instead. During matrix generation from Cholesky factors no dense matrices should ever be created to allow creation of very large matrices without memory overflow.

```python
  chol = np.eye(dim)
  num_off_diag_cholesky = int(0.5 * dim * (dim - 1))
  num_nonzero_entries = int(num_off_diag_cholesky * density)

  if num_nonzero_entries > 0:
      # Draw entries of lower triangle (below diagonal) according to sparsity level
      entry_ids = np.mask_indices(n=dim, mask_func=np.tril, k=-1)
      idx_samples = random_state.choice(
          a=num_off_diag_cholesky, size=num_nonzero_entries, replace=False
      )
      nonzero_entry_ids = (entry_ids[0][idx_samples], entry_ids[1][idx_samples])

      # Fill Cholesky factor
      chol[nonzero_entry_ids] = random_state.uniform(
          low=chol_entry_min, high=chol_entry_max, size=num_nonzero_entries
      )

  return chol @ chol.T
```

# ToDo
- [ ] Replace `random_state` input argument with `np.random.Generator`
- [ ] Create the cholesky factor `chol` using `csr_matrix((data, (row_ind, col_ind)), [shape=(M, N)])` to obtain a sparse array 
- [ ] Make sure the multiplication `chol @ chol.T` results in a `csr_matrix`
